"""Added Test Model, Changed foreign key for patients from Laboratory to Tests

Revision ID: c1fca3a1a424
Revises: 
Create Date: 2023-09-23 10:11:34.708052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1fca3a1a424'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('section')
    op.drop_table('laboratory')
    op.drop_table('test')
    op.drop_table('reception')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('patients_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tests', ['test_id'], ['id'])
        batch_op.drop_column('laboratory_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('laboratory_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('patients_ibfk_1', 'laboratory', ['laboratory_id'], ['id'])
        batch_op.drop_column('test_id')

    op.create_table('reception',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], name='reception_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.username'], name='reception_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('test',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('section_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], name='test_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('laboratory',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('section',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('laboratory_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratory.id'], name='section_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('tests')
    op.drop_table('Section')
    # ### end Alembic commands ###
